# Generated by Django 4.2.7 on 2023-11-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='profile_pic',
            field=models.ImageField(null='No images', upload_to='uploads'),
            preserve_default='No images',
        ),
    ]
